name: Grammar check

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.grammar'
      - '**.txt'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.grammar'
      - '**.txt'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Run yaspeller
        run: |
          sudo npm install yaspeller -g
          yaspeller ./skill/texts.py --ignore-latin --ignore-digits